version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: smartfamily_postgres

    environment:
      POSTGRES_DB: smartfamily
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build: .
    container_name: smartfamily_app

    ports:
      - "8501:8501"

    depends_on:
      - postgres

    volumes:
      - .:/app

volumes:
  postgres_data: